# Generated by Django 4.2.4 on 2023-08-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('number_in_stock', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('C', 'Crime'), ('N', 'Non Fiction'), ('O', 'Other'), ('S', 'Sci Fi')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
